workspace:
  path: src

branches:
  - master

pipeline:
  test-bashate:
    image: webhippie/python:2
    pull: true
    commands:
      - make bashate

  notify-gitter:
    image: plugins/gitter:1
    pull: true
    secrets: [ gitter_webhook ]
    when:
      local: false
      status: [ success, failure ]
