workspace:
  base: /srv/app
  path: src/github.com/umschlag/umschlag-scripts

branches:
  - master

pipeline:
  test-shellcheck:
    image: toolhippie/shellcheck:latest
    pull: true
    commands:
      - make shellcheck

  hub-description:
    image: toolhippie/jq:latest
    pull: true
    secrets: [ docker_username, docker_password ]
    commands:
      - bash scripts/hub-description.sh
    when:
      event: [ push ]

  label-update:
    image: toolhippie/ghi:latest
    pull: true
    secrets: [ ghi_token ]
    commands:
      - bash scripts/label-update.sh
    when:
      event: [ push ]

  notify-matrix:
    image: plugins/matrix:1
    pull: true
    secrets: [ matrix_roomid, matrix_username, matrix_password ]
    when:
      local: false
      event: [ push ]
      status: [ changed, failure ]
