workspace:
  base: /srv/app
  path: src/github.com/umschlag/umschlag-scripts

branches:
  - master

pipeline:
  test-bashate:
    image: webhippie/python:2
    pull: true
    commands:
      - make bashate

  label-update:
    image: toolhippie/ghi:latest
    pull: true
    secrets: [ ghi_token ]
    commands:
      - bash scripts/label-update.sh
    when:
      events: [ push ]

  notify-matrix:
    image: plugins/matrix:1
    pull: true
    secrets: [ matrix_roomid, matrix_username, matrix_password ]
    when:
      local: false
      events: [ push ]
      status: [ changed, failure ]
