---
kind: pipeline
name: testing

platform:
  os: linux
  arch: amd64

steps:
- name: shellcheck
  image: toolhippie/shellcheck:latest
  pull: always
  commands:
  - make shellcheck

- name: dockerhub
  image: toolhippie/jq:latest
  pull: always
  environment:
    docker_username:
      from_secret: docker_username
    docker_password:
      from_secret: docker_password
  commands:
  - bash scripts/dockerhub.sh
  when:
    event:
    - push

- name: labeling
  image: toolhippie/ghi:latest
  pull: always
  environment:
    ghi_token:
      from_secret: ghi_token
  commands:
  - bash scripts/labeling.sh
  when:
    event:
    - push

- name: notify
  image: plugins/matrix:1
  pull: always
  settings:
    username:
      from_secret: matrix_username
    password:
      from_secret: matrix_password
    roomid:
      from_secret: matrix_roomid
  when:
    event:
    - push
    - tag
    status:
    - failure

trigger:
  ref:
  - refs/heads/master
  - refs/tags/**
  - refs/pull/**
