workspace:
  path: src

pipeline:
  build:
    image: webhippie/python:2
    pull: true
    commands:
      - make deps
      - make test

  gitter:
    image: plugins/gitter:1
    pull: true
    secrets: [ gitter_webhook ]
    when:
      local: false
      status: [ success, failure ]
