workspace:
  base: /srv/app
  path: src/github.com/umschlag/umschlag-scripts

branches:
  - master

pipeline:
  test-bashate:
    image: webhippie/python:2
    pull: true
    commands:
      - make bashate

  notify-matrix:
    image: plugins/matrix:1
    pull: true
    secrets: [ matrix_roomid, matrix_username, matrix_password ]
    when:
      local: false
      events: [ push, tag ]
      status: [ changed, failure ]
